/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Usuarios;

/**
 *
 * @author diego
 */
public class Contenedor extends javax.swing.JFrame {

    /**
     * Creates new form Contenedor
     */
    Usuarios mod;
    public Contenedor() {
        initComponents();
    }
    Contenedor(Usuarios mod) {
        initComponents();
        setLocationRelativeTo(null);
        this.mod = mod;

        if (mod.getIdTipo() == 1) {
            MenuAbrir.setVisible(true);
            MenuAyuda.setVisible(true);
            MenuCatalogos.setVisible(true);
            MenuHerramientas.setVisible(true);
            MenuInformes.setVisible(true);
            MenuProcesos.setVisible(true);
        } else {
            MenuAbrir.setVisible(true);
            MenuAyuda.setVisible(true);
            MenuCatalogos.setVisible(false);
            MenuHerramientas.setVisible(false);
            MenuInformes.setVisible(true);
            MenuProcesos.setVisible(true);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAbrir = new javax.swing.JMenu();
        MenuCatalogos = new javax.swing.JMenu();
        MenuProcesos = new javax.swing.JMenu();
        MenuInformes = new javax.swing.JMenu();
        MenuHerramientas = new javax.swing.JMenu();
        MenuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        MenuAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Open_16x16.png"))); // NOI18N
        MenuAbrir.setText("Abrir");
        MenuAbrir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(MenuAbrir);

        MenuCatalogos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Folder_16x16.png"))); // NOI18N
        MenuCatalogos.setText("Catalogos");
        MenuCatalogos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(MenuCatalogos);

        MenuProcesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Check_16x16.png"))); // NOI18N
        MenuProcesos.setText("Procesos");
        MenuProcesos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(MenuProcesos);

        MenuInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Picture_16x16.png"))); // NOI18N
        MenuInformes.setText("Informes");
        MenuInformes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(MenuInformes);

        MenuHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Settings_16x16.png"))); // NOI18N
        MenuHerramientas.setText("Herramientas");
        MenuHerramientas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuHerramientas.setHideActionText(true);
        jMenuBar1.add(MenuHerramientas);

        MenuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Help_16x16.png"))); // NOI18N
        MenuAyuda.setText("Ayuda");
        MenuAyuda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(MenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contenedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAbrir;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenu MenuCatalogos;
    private javax.swing.JMenu MenuHerramientas;
    private javax.swing.JMenu MenuInformes;
    private javax.swing.JMenu MenuProcesos;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
