/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Conexion;
import Modelo.Hash;
import Modelo.SqlUsuarios;
import Modelo.Usuarios;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class FrmRegistro extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistro
     */
    
    public void loadTipo()
    {
        try
        {
            Conexion con = new Conexion();
            Connection cn = con.getConexion();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT id FROM tipo_usuario");
            JCmbTipo.removeAllItems();
            while(rs.next()){
                JCmbTipo.addItem(rs.getString(1));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }
    public FrmRegistro() {
        initComponents();
        loadTipo();
    }
    
    private void limpiar() {
        txtUsuario.setText("");
        txtPassword.setText("");
        txtConfPass.setText("");
        txtNombre.setText("");
        txtEmail.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelRegistro = new javax.swing.JPanel();
        JPanelInfoRegistro = new javax.swing.JPanel();
        JLUsuario = new javax.swing.JLabel();
        JLContra = new javax.swing.JLabel();
        JLConCon = new javax.swing.JLabel();
        JLNom = new javax.swing.JLabel();
        JLEmail = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtConfPass = new javax.swing.JPasswordField();
        JBtnAcceso = new javax.swing.JButton();
        JBtnRegresar = new javax.swing.JButton();
        JCmbTipo = new javax.swing.JComboBox<>();
        JLTipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Usuarios");
        setResizable(false);

        JPanelRegistro.setBackground(new java.awt.Color(204, 204, 204));

        JPanelInfoRegistro.setBackground(new java.awt.Color(204, 204, 204));
        JPanelInfoRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        JLUsuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        JLUsuario.setText("Usuario:");

        JLContra.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        JLContra.setText("Contraseña:");

        JLConCon.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        JLConCon.setText("Confirmar Contraseña:");

        JLNom.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        JLNom.setText("Nombre:");

        JLEmail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        JLEmail.setText("Email:");

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtConfPass.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        JBtnAcceso.setBackground(new java.awt.Color(51, 0, 51));
        JBtnAcceso.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        JBtnAcceso.setForeground(new java.awt.Color(255, 255, 255));
        JBtnAcceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Add_24x24.png"))); // NOI18N
        JBtnAcceso.setText("Registrar");
        JBtnAcceso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAccesoActionPerformed(evt);
            }
        });

        JBtnRegresar.setBackground(new java.awt.Color(51, 0, 51));
        JBtnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        JBtnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        JBtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Log Out_24x24.png"))); // NOI18N
        JBtnRegresar.setText("Regresar");
        JBtnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnRegresarActionPerformed(evt);
            }
        });

        JCmbTipo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        JLTipo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        JLTipo.setText("Tipo de Usuario:");

        javax.swing.GroupLayout JPanelInfoRegistroLayout = new javax.swing.GroupLayout(JPanelInfoRegistro);
        JPanelInfoRegistro.setLayout(JPanelInfoRegistroLayout);
        JPanelInfoRegistroLayout.setHorizontalGroup(
            JPanelInfoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelInfoRegistroLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(JPanelInfoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelInfoRegistroLayout.createSequentialGroup()
                        .addGroup(JPanelInfoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLConCon)
                            .addComponent(JLUsuario)
                            .addComponent(JLContra))
                        .addGap(22, 22, 22)
                        .addGroup(JPanelInfoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtConfPass)
                            .addComponent(txtUsuario)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPanelInfoRegistroLayout.createSequentialGroup()
                        .addGroup(JPanelInfoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLNom)
                            .addComponent(JLEmail)
                            .addComponent(JLTipo))
                        .addGap(56, 56, 56)
                        .addGroup(JPanelInfoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail)
                            .addComponent(txtNombre)
                            .addGroup(JPanelInfoRegistroLayout.createSequentialGroup()
                                .addComponent(JCmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelInfoRegistroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBtnAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBtnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        JPanelInfoRegistroLayout.setVerticalGroup(
            JPanelInfoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelInfoRegistroLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(JPanelInfoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelInfoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLContra)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelInfoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLConCon)
                    .addComponent(txtConfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelInfoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNom)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelInfoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelInfoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(JPanelInfoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnAcceso)
                    .addComponent(JBtnRegresar))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout JPanelRegistroLayout = new javax.swing.GroupLayout(JPanelRegistro);
        JPanelRegistro.setLayout(JPanelRegistroLayout);
        JPanelRegistroLayout.setHorizontalGroup(
            JPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelInfoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPanelRegistroLayout.setVerticalGroup(
            JPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelInfoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnRegresarActionPerformed
        this.dispose();
        FrmInicio frmInicio = new FrmInicio();
        frmInicio.setVisible(true);
    }//GEN-LAST:event_JBtnRegresarActionPerformed

    private void JBtnAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAccesoActionPerformed
        SqlUsuarios modSql = new SqlUsuarios();
        Usuarios mod = new Usuarios();

        String pass = new String(txtPassword.getPassword());
        String passC = new String(txtConfPass.getPassword());

        if (txtUsuario.getText().equals("") || pass.equals("") || passC.equals("") || txtNombre.getText().equals("") || txtEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios, debe llenar todos los datos");
        } else {

            if (pass.equals(passC)) {

                if (modSql.existeUsuario(txtUsuario.getText()) == 0) {

                    if (modSql.esEmail(txtEmail.getText())) {

                        String nuevoPass = Hash.sha1(pass);

                        mod.setUsuario(txtUsuario.getText());
                        mod.setPassword(nuevoPass);
                        mod.setNombre(txtNombre.getText());
                        mod.setEmail(txtEmail.getText());
                        int idTipo=0;
                        idTipo = Integer.parseInt(JCmbTipo.getSelectedItem().toString());
                        mod.setIdTipo(idTipo);

                        if (modSql.registrar(mod)) {
                            JOptionPane.showMessageDialog(null, "Registro Guardado");
                            limpiar();
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al Guardar");
                            limpiar();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El email es incorrecto");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario ya existe");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            }
        }
    }//GEN-LAST:event_JBtnAccesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnAcceso;
    private javax.swing.JButton JBtnRegresar;
    private javax.swing.JComboBox<String> JCmbTipo;
    private javax.swing.JLabel JLConCon;
    private javax.swing.JLabel JLContra;
    private javax.swing.JLabel JLEmail;
    private javax.swing.JLabel JLNom;
    private javax.swing.JLabel JLTipo;
    private javax.swing.JLabel JLUsuario;
    private javax.swing.JPanel JPanelInfoRegistro;
    private javax.swing.JPanel JPanelRegistro;
    private javax.swing.JPasswordField txtConfPass;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
